name: merge script
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0/4 * * *
  push:
    branches:
    - main
    paths-ignore:
    - "**/README.md"
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: checkout script
      uses: actions/checkout@master
      with:
        repository: gohopo/SubMerge
        ref: release
        token: ${{ secrets.GH_TOKEN }}
        path: scripts

    - name: move scripts
      run: mv scripts/* .

    - name: setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '9.0.x'

    - name: run merge
      run: ./SubMerge

    - name: push to sub branch
      run: |
        cd sub || exit 1
        git init
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b sub
        git add .
        git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin sub
